### ISSUE TITLE
Clarification on Licensing

### ISSUE THREAD

**Issue by millerserhii** [leoMirandaa/shadcn-vue-landing-page#49]
Hi Leopoldo,

First, I want to thank you for sharing your work on this project. I've found it incredibly useful and would like to explore using it in my project.

I noticed that the repository currently does not have an explicit license attached. Since GitHub repositories without licenses default to "all rights reserved," this means I don't have the legal rights to use, modify, or distribute the code.

Could you please clarify the licensing terms you're intending to apply to this project? If you're open to suggestions, licenses like the MIT License or Apache 2.0 are popular choices that encourage collaboration while maintaining some level of protection.

Thank you for your time, and I look forward to your response.

Best regards,
Sergej

**Comment by leoMirandaa** [comment]
Hello @millerserhii 

Thank you!
I have already added the MIT license to this project.
